### ISSUE TITLE
zone forward

### ISSUE THREAD

**Issue by stutiredboy** [kenshinx/godns#18]
such as: forward demo.example.com to another cache server, than any domain of *.demo.exmaple.com will query from the special cache server.

**Comment by kenshinx** [comment]
I think @bigeagle  has implemented part of function in #6 , `domain support specific upstream resolve server`. I didn't merge the function into master at that time, because i thought that's may not be needful for the mainstream scenario.However, I will rethink the possibility of merging the PR  in order to fix your requirements. 

kenshin

**Comment by kenshinx** [comment]
I re-read your PR, i guess  what you really wantted is wildcard supported?
Please check https://github.com/kenshinx/godns/issues/16 , i have provide wildcard syntax implemetation.
Similar as *.demo.example.com hosts records in redis-backend can been recognited now.

**Comment by kenshinx** [comment]
Fixed

**Comment by kenshinx** [comment]
I think I misunderstand the previous requirement and this feature has been well implemented in https://github.com/kenshinx/godns/issues/37
